### ISSUE TITLE
typing bind- in .cshtml crashes Visual studio

### ISSUE THREAD

**Issue by dlr1** [aspnet/Blazor#603] opened 2018-04-18 13:18 UTC
If I type bind- it is fine. typing any characters after - crashes Visual studio

**Comment by SteveSandersonMS** [comment] 2018-04-18 15:33
Agreed it is a duplicate of #597. Sorry for the inconvenience. I expect we'll have a fixed build soon.

**Closed by SteveSandersonMS** 2018-04-18 15:33 UTC
