### ISSUE TITLE
Execution error in Windows 7

### ISSUE THREAD

**Issue by Bitexirtz** [aspnet/Blazor#487] opened 2018-04-04 22:54 UTC
Execution error in Windows 7.

Steps: (after installing https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview1)
1. dotnet new -i Microsoft.AspNetCore.Blazor.Templates
2. dotnet new blazor -o BlazorApp1
3. cd BlazorApp1
4. dotnet run

Result:
Using launch settings from D:\projects\blazor\BlazorApp1\Properties\launchSettings.json...
Application startup exception: System.InvalidOperationException: Cannot find bin directory for Blazor app. Neither 'D:\projects\blazor\BlazorApp1\bin\Debug' nor 'D:\projects\blazor\BlazorApp1\bin\Release' exists on disk. Make sure the project has been built.
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientBinDir(String clientAppSourceRoot)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientAssemblyPath(IApplicationBuilder app)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Cannot find bin directory for Blazor app. Neither 'D:\projects\blazor\BlazorApp1\bin\Debug' nor 'D:\projects\blazor\BlazorApp1\bin\Release' exists on disk. Make sure the project has been built.
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientBinDir(String clientAppSourceRoot)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientAssemblyPath(IApplicationBuilder app)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by SteveSandersonMS** [comment] 2018-04-04 22:58
Is it true that neither the `Debug` nor `Release` directories exists in those locations?

Could you run `dotnet build` and see if it succeeds and creates the `Debug` directory?

Could you also run `dotnet --version` inside your application directory and confirm what it tells you?

**Comment by Bitexirtz** [comment] 2018-04-04 23:01
Please see below.

D:\projects\blazor\BlazorApp1>dotnet --version
2.1.300-preview1-008174

D:\projects\blazor\BlazorApp1\bin\BPC\Debug\netstandard2.0>dir
 Volume in drive D is Data
 Volume Serial Number is 6020-9FB1

 Directory of D:\projects\blazor\BlazorApp1\bin\BPC\Debug\netstandard2.0

04/05/2018  06:36 AM    <DIR>          .
04/05/2018  06:36 AM    <DIR>          ..
04/05/2018  06:52 AM               190 BlazorApp1.blazor.config
04/05/2018  06:36 AM            15,872 BlazorApp1.dll
04/05/2018  06:36 AM             1,160 BlazorApp1.pdb
04/05/2018  06:36 AM    <DIR>          dist
03/22/2018  06:06 PM            27,624 Microsoft.AspNetCore.Blazor.Browser.dll
03/22/2018  06:06 PM            89,576 Microsoft.AspNetCore.Blazor.dll
01/25/2018  06:47 AM            36,360 Microsoft.Extensions.DependencyInjection.
Abstractions.dll
01/25/2018  06:47 AM            44,552 Microsoft.Extensions.DependencyInjection.
dll
               7 File(s)        215,334 bytes
               3 Dir(s)  268,928,122,880 bytes free

**Comment by SteveSandersonMS** [comment] 2018-04-04 23:32
The issue is the BPC directory. What causes that to exist? It’s not there by default.

**Comment by Bitexirtz** [comment] 2018-04-04 23:37
I only did the steps below. No additional steps.
I tried in Windows 10 and I executed successfully with same steps.

Steps:
1. dotnet new -i Microsoft.AspNetCore.Blazor.Templates
2. dotnet new blazor -o BlazorApp1
3. cd BlazorApp1
4. dotnet run

**Comment by Bitexirtz** [comment] 2018-04-04 23:39
I tried to move out "bin" from "BCP" and was able to execute successfully in Windows 7.
I wonder why how "BCP" was created or what creates it.

**Comment by Bitexirtz** [comment] 2018-06-15 23:36
Still exists even using .NET Core 2.1 SDK (v2.1.300).

**Comment by SteveSandersonMS** [comment] 2018-07-23 22:13
It doesn't look like this affects anybody except the original poster, and even then only on one PC. It's quite possible that some unrelated software running on that PC is interfering.

Since we're not realistically going to be able to do anything about this without a repro or at least multiple independent reports, I'll close this.

@Bitexirtz If you have found any further info in the meantime that would give us clues about how to repro it, please let us know!

**Closed by SteveSandersonMS** 2018-07-23 22:13 UTC

**Comment by Bitexirtz** [comment] 2018-07-23 22:41
I'm using our office PC in producing this error. Even using docker on the same PC, I can produce the same error.
Maybe this error is due to Windows policy implemented by our Admin besides we are behind a proxy. At home, using Windows 10, I don't encounter this error. I will try using other office PC and if I determined the cause, I will just inform again here.
Thank you for you support. Nice work! (Waiting for 1.0)
