### ISSUE TITLE
New logo design.

### ISSUE THREAD

**Issue by jraulhernandezi** [aspnet/Blazor#714] opened 2018-04-30 19:35 UTC
Hi guys, would you like a new logo design you you project? 
I could send you some ideas, let me know.

**Comment by danroth27** [comment] 2018-04-30 20:29
Thanks for offering to help out, @jraulhernandezi! You're welcome to propose ideas in #430, but we will most likely produce something internally. Closing this as a duplicate of #430.

**Closed by danroth27** 2018-04-30 20:29 UTC
