### ISSUE TITLE
Update project template to describe problems with add blockers

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor#655] opened 2018-04-23 11:12 UTC
There are a lot of users who have different add blockers in their browsers. They open https://blazor-demo.github.io/ or they create demo project and publish to Azure. They see Loading... and that is all. I think it is a good idea to describe the problem in `<div id="app">Loading...</div>`. Otherwise people may think that Blazor is useless product, and we all know that it is exactly opposite - it is a revolution!

It will be a good idea to update demo app here https://blazor-demo.github.io/. Current version with Bootstrap 4 looks much better.

**Comment by SteveSandersonMS** [comment] 2018-04-23 12:31
Thanks for the suggestion, but whatever time we would spend doing this I'd rather spend fixing the underlying issue.

I'm assuming you're referring to #172, right? Do you have any specific repro steps to show the scenario where things are blocked? By specific, I mean which *specific ad blocker products* and in what specific configuration it causes an issue. If you do, could you post them to #172 so we make sure we account for all such scenarios when fixing it?

I'll close this as a duplicate of #172 since that's where we'd do the fix.

**Closed by SteveSandersonMS** 2018-04-23 12:31 UTC
