### ISSUE TITLE
Error when bind bootstrap custom attribute

### ISSUE THREAD

**Issue by dimabayda** [aspnet/Blazor#728] opened 2018-05-01 20:33 UTC
Hello, i have an error when bind some string to bootstrap custom attribute (consist of two parts connected by a hyphen).

Code example where error occurs:
`<button type="button" class="@ButtonClass" data-target="@TargetId" data-toggle="modal">
	@ButtonCaption
</button>`

![image](https://user-images.githubusercontent.com/15806101/39492155-5d3b8b3a-4d97-11e8-8b77-a69db9a8e4e4.png)

I think, its related to new "bind-" syntax.

**Comment by SteveSandersonMS** [comment] 2018-05-01 20:49
Please replace `data-something` with `data_something`.

This is a workaround for an issue we're tracking at https://github.com/aspnet/Blazor/issues/297, so closing as a duplicate of that.

**Closed by SteveSandersonMS** 2018-05-01 20:49 UTC
