### ISSUE TITLE
Blazor with Kelstrel crashes vs

### ISSUE THREAD

**Issue by srburton** [aspnet/Blazor#1328] opened 2018-08-17 02:27 UTC
Blazor with Kelstrel causes vs. locking.
I'm facing a problem with the Kestrel every time I start for the second time the app it causes Visual Studio locking and then closing, this is happening to all friends I know is a shame.
  The problem seems to be because when stopped the build it keeps running in the background when started again as already has use of the delivery and the service causes this fatal error.

**Comment by SteveSandersonMS** [comment] 2018-08-17 15:33
Sorry to hear this is happening.

It's not something that I've personally observed, nor do I have any idea how to reproduce it. If you know any steps that cause this to happen (based on an up-to-date VS 15.7 and .NET Core SDK 2.1.0) please tell us.

Likewise if anyone else is experiencing this, please provide any info you might have about how to trigger it.

**Comment by renatoprogramer** [comment] 2018-08-17 16:52
`dotnet --version` & `dotnet --info`
![screenshot_6](https://user-images.githubusercontent.com/15394508/44278196-a45e5200-a223-11e8-86d2-523c79e93868.jpg)

`Activate Kestrel `
![screenshot_7](https://user-images.githubusercontent.com/15394508/44278299-f56e4600-a223-11e8-87ec-0d0f92e41328.jpg)

`Solution Property`
![screenshot_8](https://user-images.githubusercontent.com/15394508/44278501-81806d80-a224-11e8-9db3-f90d0aaadd4c.jpg)

`Settings`
![screenshot_9](https://user-images.githubusercontent.com/15394508/44278553-abd22b00-a224-11e8-846b-b901ea56d9bd.jpg)

**Comment by danroth27** [comment] 2018-08-17 16:57
Is this a standalone Blazor project, or an ASP.NET Core hosted project?

**Comment by danroth27** [comment] 2018-08-17 16:59
Also, do you have a *global.json* file in this project? If yes, what does it contain?

**Comment by renatoprogramer** [comment] 2018-08-17 17:06
![screenshot_10](https://user-images.githubusercontent.com/15394508/44279120-a2e25900-a226-11e8-86de-6dd18c6ca0d6.jpg)

**Comment by renatoprogramer** [comment] 2018-08-17 17:07
![screenshot_11](https://user-images.githubusercontent.com/15394508/44279193-dcb35f80-a226-11e8-9aff-b521935e1955.jpg)

**Comment by danroth27** [comment] 2018-08-17 17:08
Thanks! One more question: which version of VS do you have? Did this issue only start occurring after installing 15.8? Or are you seeing this on 15.7?

**Comment by renatoprogramer** [comment] 2018-08-17 17:10
![screenshot_12](https://user-images.githubusercontent.com/15394508/44279294-459ad780-a227-11e8-8a9c-3e0e06acc344.jpg)

**Comment by danroth27** [comment] 2018-08-17 17:18
Great, thx!

I'm trying to reproduce this issue. I have VS 15.8 installed and I have both the 2.1.300 and 2.1.400 .NET Core SDKs installed.

I've tried the following:
- Create a new Blazor app
- Switch from running the project on IIS Express to running on Kestrel 
- Ctrl-F5 to run the app, works fine
- Make a change to the app (edit Counter.cshtml)
- Hit Ctrl-F5 to run the app again, works fine
- Hit Ctrl-C to stop the app
- Make another edit
- Ctrl-F5 to run again, works fine

Any suggestions on how to reproduce this? Is it possible for you to share your exact project with us and specific repro steps?

**Comment by renatoprogramer** [comment] 2018-08-17 17:31
**Try to edit a file with the running application**

![screenshot_13](https://user-images.githubusercontent.com/15394508/44279986-c8bd2d00-a229-11e8-9e33-0733cfa2abe5.jpg)

**Comment by renatoprogramer** [comment] 2018-08-17 17:36
![screenshot_14](https://user-images.githubusercontent.com/15394508/44280357-e63ec680-a22a-11e8-938c-fed3f102abeb.jpg)

**Comment by danroth27** [comment] 2018-08-17 17:45
Oh, are you trying to run a stand-alone Blazor app under the debugger (F5 instead of Ctrl-F5)? Unfortunately, that's not currently supported. Remember that client-side Blazor apps run on WebAssembly in the browser, where there is no native capability to attach a .NET debugger. We do have some [very early support for debugging client-side Blazor apps](https://blogs.msdn.microsoft.com/webdev/2018/07/25/blazor-0-5-0-experimental-release-now-available/) using the Chrome dev tools, but it's *very* rough right now.


Even so, we shouldn't be crashing VS. If I run the app under the debugger (F5 instead of Ctrl-F5) and then edit I file I do see the dialog asking about stopping the debugger after I refresh the browser. But, I still don't VS to crash. I've tried stopping the debugger, leaving it attached, and just waiting.

**Comment by renatoprogramer** [comment] 2018-08-20 01:51
Resolved `Ctrl + F5 ` in Visual Studio and it seems to work :-)

**Comment by danroth27** [comment] 2018-08-20 20:36
Cool. It would still be good to track down the crash, but to do that we need a stack trace. If you can collect a VS activity log that shows the stack trace of the exception that caused the VS crash we can take a look.

**Comment by danroth27** [comment] 2018-08-20 20:39
Docs on collecting a VS activity log can be found here: https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe

**Comment by WhiteBookmark** [comment] 2018-09-11 21:53
I tried using Ctrl + F5 but it throws an error

![blazortest](https://user-images.githubusercontent.com/37548818/45389963-fcc41c00-b636-11e8-82aa-b69982559f0e.PNG)

**Comment by srburton** [comment] 2018-09-12 12:09
@WhiteBookmark  Open your CMD in the project folder and run the following command  "dotnet--info " and send me the print so I see something if you can send me a print also from the Build Setup screen would be a good,

**Comment by WhiteBookmark** [comment] 2018-09-12 16:11
@srburton 
Attached both screenshots:

![cmd](https://user-images.githubusercontent.com/37548818/45438381-6f350a80-b6d0-11e8-8e6f-b7943424c7f5.PNG)
![rebuild](https://user-images.githubusercontent.com/37548818/45438388-74925500-b6d0-11e8-9a9d-b0489b852728.PNG)

**Comment by srburton** [comment] 2018-09-13 01:30
@WhiteBookmark 
The global.json specifies the SDK version of .NET Core that is being used to build your application. This has little to do with the .NET Core Runtime version that you want to run your application with.

Your application is a netcoreapp2.1, so you are running the .NET Core 2.1 Runtime. The earliest SDK Version for that is 2.1.300.

Since that is the latest .NET Core version, you actually don’t need to use a global.json at all: Just delete the file from your project and the tooling should use the latest version which is 2.1.300-rc1 on your machine.

**Comment by srburton** [comment] 2018-09-13 01:32
Another thing is to update your Visual Studio, from a look at that flag that is yellow in your Visual Studio and see the updates thinking

**Comment by WhiteBookmark** [comment] 2018-09-13 20:57
@srburton 
I deleted global.json and now its working fine, thank you :)
I will update my VS, thanks for notifying

**Comment by danroth27** [comment] 2018-09-14 19:04
The global.json issue will be fixed in our next release. 

Since we don't have an activity log for this VS crash and we can't reproduce it I'm going to go ahead and close this issue.

**Closed by danroth27** 2018-09-14 19:04 UTC
