### ISSUE TITLE
The Router doesn't handle links from a deep page back to root properly

### ISSUE THREAD

**Issue by torhovland** [aspnet/Blazor#368] opened 2018-03-25 06:20 UTC
I can use a NavLink back to root on most pages, and it will work well:

```
<NavLink href="/">Home</NavLink>
```

However, if I do that on a page that is on a deeper route, such as "/products/123", the link is handled as a new request and reload of the Blazor app.

**Comment by rstropek** [comment] 2018-03-25 06:57
I have a similar demo in my [router-related chapter on learn-blazor.com](https://learn-blazor.com/pages/router/). You can find the complete sample [here on GitHub](https://github.com/software-architects/learn-blazor/tree/master/samples/RouterDemo). If I use `NavLink` or `a href` to navigate from a deep link (in my case `@page "/hello-planet/{Planet}"`) to the root (`@page "/"`), it works fine.

Maybe you find the root cause of your problem by comparing your code with mine. Let me know what the reason was, I am curious to know.

**Comment by torhovland** [comment] 2018-03-26 19:04
Hi!

It turned out that this issue was very related to the other one I logged at https://github.com/aspnet/Blazor/issues/360. Both issues were caused by not having `<base href="/" />` in my index.html.

I wouldn't have figured this out without the comments from @rstropek.

Not sure if this issue should just be closed, or whether there needs to be something in the documentation about this.

**Comment by danroth27** [comment] 2018-03-26 21:18
It's good to hear you were able to resolve your issue! We include `<base href="/" />` in the Blazor templates, so it doesn't sound like there is anything to do here in Blazor, so closing.

**Closed by danroth27** 2018-03-26 21:18 UTC
