### ISSUE TITLE
Large Projects

### ISSUE THREAD

**Issue by WayneHiller** [aspnet/Blazor#866] opened 2018-05-21 21:15 UTC
My understanding it that the entire "client" will be loaded into the browser. Has anyone tested how large a Blazor project can get before the browser starts having issues?

I have a large project that I would like to test out in Blazor but it is too large (I think) for a single SPA. Has there been any discussion around the ability to maybe have some kind of modules that could be loaded from a URL server side? 

Is there any way to do this kind of thing currently? So just as an example my project might have a Sales module, Customers module, Inventory module etc.  Each module could be loaded into the browser as it's own "Blazor" client side package. Some how the Server would need to know what "module" to send to the browser when it receives a request for one.

**Comment by Andrzej-W** [comment] 2018-05-21 21:45
Lazy loading is tracked here: #25.

Hopefully it will solve our problem. I also have a big LOB application with more than 100 modules (client-server desktop app written in C++). I spend at least a few hours a day working with Blazor. I'm impressed and I believe that it will change the world.

**Comment by WayneHiller** [comment] 2018-05-21 21:55
Agreed, I believe Razor has a bright future and the time to get involved is now. I will check out the Lazy loading thread, maybe start contributing as well. Thanks.

**Comment by richbryant** [comment] 2018-05-22 07:28
yes, but... The way I'd go about this in Angular or Aurelia is not to build a single SPA but rather a set of SPAs, much as the last line of your comment indicates.  A set of Blazor front-end applications with a Shared project should work much the same way, especially if served from the same CDN, and of course, you still get the benefit of sharing code between the client and server.  And a single language to maintain.

Seems to me that regardless of the language or framework they're written in, browser apps are browser apps and follow a certain set of patterns.  These obviously aren't identical to those we use in monolithic LOB application due to the constraints of the client so some adjustments must be made.

**Comment by babula38** [comment] 2018-05-22 07:56
@WayneHiller i guess the [issue#25](https://github.com/aspnet/Blazor/issues/25) may answer your questions. Just check the last comment from @danroth27

**Comment by SteveSandersonMS** [comment] 2018-05-22 09:12
I'll close this as a duplicate of #25.

**Closed by SteveSandersonMS** 2018-05-22 09:12 UTC
