### ISSUE TITLE
Blazor 0.2.0 applications fail to load in Safari on macOS/iOS

### ISSUE THREAD

**Issue by panesofglass** [aspnet/Blazor#625] opened 2018-04-20 04:02 UTC
### Environment:
- macOS High Sierra 10.13.4 (17E199)
- dotnet 2.1.300-preview2-008533
- Blazor 0.2.0

### Repro steps:
1. Create a blazer stand-alone (or hosted) app from the latest templates
2. Build with `dotnet build $project`
3. Run with `dotnet run --project $project`

### Expected:
Blazor app runs in Safari as it did for the 0.1.0 runtime and templates

### Actual
- Safari attempts to load and fails with `This webpage was reloaded because a problem occurred.`
- Safari attempts to reload.
- Safari stops trying to reload after repeated failures.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/8803/39030186-b67c2e96-4425-11e8-89dd-64cf3b4158c0.png">

### Additional details:
- I attempted to open the JavaScript Console to see what was happening, but the console is closed due to the errors.
- I don't see any errors in the logs, just repeated requests for the same files with the expected HTTP `304` responses.

**Comment by danroth27** [comment] 2018-04-20 04:04
@SteveSandersonMS Looks like we're still having issues with Safari.

**Comment by panesofglass** [comment] 2018-04-20 04:05
I'm happy to provide any additional details you may need if I can get them.

**Comment by muqeet-khan** [comment] 2018-04-20 14:50
Same issue, mobile environment.

Environment:
iPhone 7s Version 11.2.6 (15D100)
Blazor 0.2.0 Standalone Application published on Azure.

Repro steps:
Browse https://learningblazor.azurewebsites.net from iPhone 7s

Expected:
Show up properly as it does on windows desktop machine on both Chrome and edge.

Actual:
Safari attempts to load and fails and stuck at "Loading ..."
Google Chrome on iOS attempts to load and fails and stuck at "Loading ..."

Works just fine on Android on all browsers I tested with so I am assuming it has something to do with Mac and iOS rather than the browsers on that platform. :-(

**Comment by panesofglass** [comment] 2018-04-20 21:11
Chrome and Firefox work fine for me on macOS.

**Comment by danroth27** [comment] 2018-04-20 21:16
@Kumpera This issue is being reported for macOS High Sierra. Do we potentially have Mono misconfigured in Blazor?

@muqeet-khan The issue for mobile Safari is known and is being investigated by the Mono team in conjunction with Apple.

**Comment by panesofglass** [comment] 2018-04-22 04:37
Safari 11.1 (13605.1.33.1.2)

**Comment by kumpera** [comment] 2018-04-23 15:27
WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=184829

**Comment by kumpera** [comment] 2018-04-23 15:41
As it turns out, all crashes, mobile and desktop safari, share the same underlying bug.

**Comment by vertonghenb** [comment] 2018-06-16 21:09
I can confirm that this is **solved** on Safari for Mac 11.1.1

<img width="1439" alt="screen shot 2018-06-16 at 23 04 17" src="https://user-images.githubusercontent.com/10981553/41502440-363f10d2-71ba-11e8-9a1b-3d06a64682dc.png">

**Comment by SteveSandersonMS** [comment] 2018-06-16 21:16
@vertonghenb Unfortunately that doesn't confirm it, because that site is running a much older runtime that wasn't affected. A valid test would be with http://blazor-flight-finder.azurewebsites.net/, but I don't think you'll find it's fixed in 11.1.1 since the underlying issue was only addressed in Webkit sources in the last week.

**Comment by Daddoon** [comment] 2018-06-21 15:29
For this issue, rolling back to asmjs on theses specific buggy Webkit version seem to solve the problem, but of course you can feel the performance drawback at startup.

I will try to address an update on my Blazor.Polyfill project tomorrow, in order to workaround to asmjs on theses specific Safari version. Better than nothing...

**Comment by Daddoon** [comment] 2018-06-22 13:47
@vertonghenb [Updated my projects](https://github.com/Appizeo/Blazor.Polyfill/releases) if you want to have a fallback to asmjs on theses specific Webkit versions.

**Comment by Daddoon** [comment] 2018-07-03 20:12
As a side note for this thread, nothing more is necessary if people use my last version **Blazor.Polyfill** , as only a range of Webkit version was checked at startup.

It should work as WebAssembly (normal behavior) at startup of Blazor app.

**Comment by SteveSandersonMS** [comment] 2018-07-23 22:09
This was confirmed fixed in iOS 12.

Anyone who needs iOS 11 support should use @Daddoon's polyfill.

**Closed by SteveSandersonMS** 2018-07-23 22:09 UTC
Labels: external

**Comment by pheuter** [comment] 2019-06-25 14:23
Blazor apps don't appear to be working in the latest iOS 13 beta as well as macOS Catalina.

**Comment by Daddoon** [comment] 2019-06-25 15:32
This repository is closed, as far as i know, and everything merged to aspnet components.
By the way, wich version of Blazor have you tested ? This thread was about 0.2.0.

**Comment by danroth27** [comment] 2019-06-25 15:42
@pheuter Thanks for letting us know! We're looking into it.

**Comment by pheuter** [comment] 2019-06-25 15:46
@danroth27 Awesome, thanks!

@Daddoon Gotcha, yeah figured I'd just post here since the thread seemed potentially relevant, but also aware that Blazor is now officially supported by the core asp.net team. I'm on version `3.0.0-preview5-19227-01` and using the ASP.NET Core Hosted client-side model.

**Comment by chucker** [comment] 2019-06-25 18:45
@danroth27 this is probably http://www.openradar.me/50400451

I've seen this with any client-side Blazor page on Safari 13.x (the current release build Safari 12.1.1 is fine).
