### ISSUE TITLE
Authentication for serverside blazor

### ISSUE THREAD

**Issue by floreseken** [aspnet/Blazor#1554] opened 2018-10-12 08:33 UTC
I've read this: https://github.com/aspnet/Blazor/issues/1449
and this: https://github.com/aspnet/Blazor/issues/698

And still have some questions. 
The last option (of 1449) kind of defeats the purpose of SS blazor in my opinion. This way you are losing lots of the benefits. (creating a API surface and client), but that will work.

And the first option can only be used to control access to the whole application, right? Not to identify users in the components code.

For instance, I would like to be able to use:

`Thread.CurrentPrincipal` 

in my components, but enabling authentication(in the server part) does not provide this (always null). I kind of understand why.. the SignalR stuff bypasses everything of the default stack, and provides no auth bearer or something, I guess?

In my opinion being able to use a principal in serverside blazor essential for enterprise applications.
Am I missing something? Or is this not possible yet? And is my scenario covered by 698?

Thanks

**Comment by cores-system** [comment] 2018-10-12 19:03
@floreseken, You can use IHttpContextAccessor to send the current HttpContext to blazor.Client.

**Comment by cores-system** [comment] 2018-10-12 19:14
**blazor.Sever to Startup.cs**

```cs
public void ConfigureServices(IServiceCollection services)
{
    services.AddServerSideBlazor<Client.Startup>();
	
    // HttpContextAccessor
    services.AddHttpContextAccessor();
    services.AddScoped<HttpContextAccessor>();
}
```

**blazor.Shared**
```cs
public class HttpContextAccessor
{
    private readonly IHttpContextAccessor _httpContextAccessor;

    public HttpContextAccessor(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public HttpContext Context => _httpContextAccessor.HttpContext;
}
```

**blazor.Client to App.cshtml**
```cs
@inject blazor.Shared.HttpContextAccessor HttpContext
<Router AppAssembly=typeof(Program).Assembly />

@functions 
{      
    protected override void OnInit()
    {
        HttpContext.Context.Request.Cookies.**
		
        // Or data passed through middleware in blazor.Server
        HttpContext.Context.Features.Get<T>()
    }
}
```

**Comment by cores-system** [comment] 2018-10-12 19:17
In `blazor.Shared` you will need to add the package [Microsoft.AspNetCore.Http](https://www.nuget.org/packages/Microsoft.AspNetCore.Http/2.1.1) via `nuget`

**Comment by ADefWebserver** [comment] 2018-10-12 21:42
Also see a GitHub example at: https://github.com/SQL-MisterMagoo/BlazorTest

**Comment by carlosalcantara2668** [comment] 2018-10-13 12:00
it worked for me !!!

**Comment by carlosalcantara2668** [comment] 2018-10-13 12:02
@cores-system , @floreseken ,
it worked for me !!!,
I have access to all the methods of the object.

**Comment by cores-system** [comment] 2018-10-13 12:07
@carlosalcantara2668, I'm glad I helped )

**Comment by roboriaan** [comment] 2018-10-15 17:13
I was wondering if it would be possible to use [Authorize] in Blazor 0.6.0 Server-side. Something like :

In FetchData.cshtml

`@using RC.App.Services`
`**@[Authorize]**`
`@page "/fetchdata"`
`@inject WeatherForecastService ForecastService`

Thanks for the great .net core stuff guys!

**Comment by danroth27** [comment] 2018-10-15 19:53
I think we have several issues open at this point tracking the need for guidance and support for authentication and authorization, so I'm going to close this one as a duplicate of #64.

**Closed by danroth27** 2018-10-15 19:53 UTC

**Comment by ADefWebserver** [comment] 2018-11-04 21:52
I created a sample and a Blog post using the code provided above: [A Demonstration of Simple Server-side Blazor Cookie Authentication](http://lightswitchhelpwebsite.com/Blog/tabid/61/EntryId/4316/A-Demonstration-of-Simple-Server-side-Blazor-Cookie-Authentication.aspx)

**Comment by rakkarage** [comment] 2019-05-15 15:53
https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md

**Comment by peteralbanese** [comment] 2019-08-03 22:22
> https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md

broken link

**Comment by travisneale** [comment] 2019-08-03 22:41
> https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md
> 
> broken link

Try this one:
https://github.com/SQL-MisterMagoo/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md
