### ISSUE TITLE
Authentication & Identity

### ISSUE THREAD

**Issue by conficient** [aspnet/Blazor#698] opened 2018-04-28 10:58 UTC
I couldn't find an issue tracking authentication and identity and how this would be handled in Blazor? I assume we would try to follow asp.net core practices on the server, but how would this be handled on the client?

I expect we'd need something in the routing engine, and possibly per-page attributes as well?

**Comment by RemiBou** [comment] 2018-05-03 07:39
I'm currently translating the existing Authentication/Authorization template to Blazor here : https://github.com/RemiBou/Toss.Blazor right now, registration, account management, openid (with google) and login are done

**Comment by danroth27** [comment] 2018-07-10 05:12
Example using ADAL.js https://gunnarpeipman.com/aspnet/blazor-azure-ad-adal/

**Comment by rezabayesteh** [comment] 2018-09-28 00:15
@vertonghenb I have exactly the same questions about ServerSideBlazor.

**Comment by danroth27** [comment] 2018-10-15 19:53
I think we have several issues open at this point tracking the need for guidance and support for authentication and authorization, so I'm going to close this one as a duplicate of #64.

**Closed by danroth27** 2018-10-15 19:53 UTC

**Comment by guardrex** [comment] 2019-02-15 00:21
Cross-ref: https://github.com/aspnet/AspNetCore/issues/5472

**Comment by danroth27** [comment] 2019-02-15 00:37
And https://github.com/aspnet/AspNetCore/issues/4048 for Razor Components

**Comment by conficient** [comment] 2019-05-03 07:19
Just like to point out a nice demo of using Identity with client-side Blazor that doesn't use an MVC pages:

https://github.com/stavroskasidis/BlazorWithIdentity

**Comment by wize1** [comment] 2019-05-07 13:41
> Just like to point out a nice demo of using Identity with client-side Blazor that doesn't use an MVC pages:
> 
> https://github.com/stavroskasidis/BlazorWithIdentity

Interesting... 

![image](https://user-images.githubusercontent.com/8410799/57303916-fd8a5080-70e6-11e9-9bd3-d8d66266693b.png)

**Comment by stavroskasidis** [comment] 2019-05-07 14:16
> > Just like to point out a nice demo of using Identity with client-side Blazor that doesn't use an MVC pages:
> > https://github.com/stavroskasidis/BlazorWithIdentity
> 
> Interesting...
> 
> ![image](https://user-images.githubusercontent.com/8410799/57303916-fd8a5080-70e6-11e9-9bd3-d8d66266693b.png)

It is a false negative, a known issue with antiviruses and blazor.

See this issue
https://github.com/aspnet/AspNetCore/issues/5477

Also read about this
https://www.starmessagesoftware.com/faq-page/what-is-avast-drep-infection

**Comment by wize1** [comment] 2019-05-07 15:41
> > > Just like to point out a nice demo of using Identity with client-side Blazor that doesn't use an MVC pages:
> > > https://github.com/stavroskasidis/BlazorWithIdentity
> > 
> > 
> > Interesting...
> > ![image](https://user-images.githubusercontent.com/8410799/57303916-fd8a5080-70e6-11e9-9bd3-d8d66266693b.png)
> 
> @wize1
> It is a false negative, a known issue with antiviruses and blazor.
> 
> See this issue
> [aspnet/AspNetCore#5477](https://github.com/aspnet/AspNetCore/issues/5477)
> 
> Also read about this
> https://www.starmessagesoftware.com/faq-page/what-is-avast-drep-infection

good to know. thanks.

**Comment by rakkarage** [comment] 2019-05-15 15:54
https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/05-authentication-and-authorization.md
