### ISSUE TITLE
Layered approach for core technologies

### ISSUE THREAD

**Issue by Andrew-Hanlon** [aspnet/Blazor#912] opened 2018-06-01 15:23 UTC
Hi there,

The Blazor initiative is really exciting, and the framework itself (over and above the .net wasm aspect) has lots of potential and nice features that I am excited to use. But, as we are all aware, SPA frameworks and approaches waver in and out of favour (fervor) quite rapidly. And, rightly or wrongly, the current front-end ecosystem thrives in a state of rapid change. Case in point, there are already several alternate '.net wasm' projects sprouting up.

With this in mind, would it make sense to push this initiative into more of a layered approach - separating out the core enabling technologies from the front-end SPA parts - to ensure that the core technologies can be developed, shared, and maintained even _if_ differing SPA approaches develop / are desired?

For example, I could imagine separating the following into composible pieces:

- wasm framework / bootstrapper,
- JS / Dom interop APIs,
- virtual dom APIs,
- routing,
- Razor components, etc.

In the back-end world (while more could be done) many of the ASP pieces can be composed and used in significantly different scenarios.

Apologies if I have missed something and a similar discussion is already in the pipeline.

Thank you kindly,

**Comment by danroth27** [comment] 2018-06-01 15:37
Thanks for the suggestion! 

Having a layered approach is certainly the intention:
- Blazor itself is primarily a Web UI framework. The .NET runtime bits are handled separately by the Mono team and like you said they are already available to be reused independently of Blazor
- We are discussing with the Mono folks how to pull out the JS interop related abstractions so they can be reused in an independent way
- On top of the JS interop abstraction we expect there will be a reusable set of browser API wrappers for .NET that anyone could use

The Blazor rendering tree, routing, and component model are Blazor specific by design and we don't really have any intention to make those separately reusable components. I suspect that alternative web UI frameworks would want to have their own designs for these components anyway.

I think this addresses your question and I don't think there is any additional work to track with this issue, so I'm going to go ahead and close it. I hope that's ok!

**Closed by danroth27** 2018-06-01 15:37 UTC

**Comment by Andrew-Hanlon** [comment] 2018-06-01 16:05
Thanks @danroth27 - that answers my question and I am looking forward to great things! 

No urgency, but other than the issues, is there another resource for keeping up with the roadmap and vision around Blazor?

Thanks again.

**Comment by RyoukoKonpaku** [comment] 2018-06-01 16:09
Great news to hear @danroth27. Definitely nice to hear on separating the JS interop coupling to standardize the .Net Wasm usage for other projects, this will solve the "reinventing the wheel" that happens all too common on the web ecosystem.

Definitely exciting times ahead.

**Comment by danroth27** [comment] 2018-06-01 16:15
@Andrew-Hanlon Right now GitHub is your best resource for getting visibility into upcoming Blazor releases. Hopefully we'll have more clarity on the roadmap for Blazor shortly.
