### ISSUE TITLE
Browser disappears when app is run

### ISSUE THREAD

**Issue by mrpmorris** [aspnet/Blazor#1257] opened 2018-08-04 10:56 UTC
I'm migrating Fluxor to the newest version of Blazor. Three of the sample projects work, but two do not (04 and 05).

When I run them the Browser (Chrome Version 68.0.3440.84 - 64 bit) opens and then immediately closes.  Looking in Fiddler it doesn't even get as far as downloading my assemblies.

I've checked and the startup.cs and program.cs in 04 are the same as in 01. Can anyone help?

https://github.com/mrpmorris/blazor-fluxor/tree/feature/UpgradeToBlazor.0.5

**Comment by SteveSandersonMS** [comment] 2018-08-06 12:00
If the browser is crashing, that's definitely a browser bug, as it should not be possible for a JS/Wasm application to make the browser crash even if it's deliberately trying to. If you can reliably repro a Chrome crash, would you consider reporting this to the Chrome team?

**Comment by Arshia001** [comment] 2018-08-06 15:59
@mrpmorris @SteveSandersonMS I've had the same thing happen to me. Inspecting the system logs revealed it was a problem with IIS express. The browser closing is just VS deciding the app has finished running. As a work around, you can just start your server in a self hosted environment instead of IIS express (select your project insteas of IIS express as VS' debug target).

**Comment by danroth27** [comment] 2018-08-06 16:39
> Inspecting the system logs revealed it was a problem with IIS express. The browser closing is just VS deciding the app has finished running. 

@Arshia001 Could you please share more details about the issue you saw with IIS express? Was this issue reported anywhere? /cc @shirhatti @BillHiebert

**Comment by danroth27** [comment] 2018-08-06 17:02
@mrpmorris I tried out samples 04 and 05. I wasn't able reproduce the browser closing issue you described. I get the HTML page and then nothing else happens. That's because the script tags in the *index.html* files for these samples still need to be updated to the new pattern.


Instead of this:

```html
<script type="blazor-boot"></script>
```


Do this:


```html
<script src="_framework/blazor.webassembly.js"></script>
```

**Closed by danroth27** 2018-08-06 17:02 UTC

**Comment by mrpmorris** [comment] 2018-08-06 21:56
@danroth27 I am aware it needs upgrading, I just find it odd that the server stops running. I'll investigate further, thanks.
