### ISSUE TITLE
When i create the app using the blazor template in VS 2017 preview i get build errors

### ISSUE THREAD

**Issue by rupamroy** [aspnet/Blazor#488] opened 2018-04-05 00:45 UTC
When i create the app using the blazor template in VS 2017 preview i get build errors as shown below. If i generate the app using cli then everything runs fine.

![image](https://user-images.githubusercontent.com/9621769/38341887-e7bcae60-3848-11e8-9dde-eab6a79560dd.png)

**Comment by rynowak** [comment] 2018-04-05 00:55
You can provide an example of what the generated code looks like? This would help me confirm what I think is the problem.

My guess is that we're not sanitizing the project directory name, which we use to infer a namespace. If you switch it to something that is a valid C# identifier this should work around the problem.

**Comment by Vertygo** [comment] 2018-04-05 07:06
Happened to me when I used hyphen  in the project name eg "Project-2018".

**Comment by SteveSandersonMS** [comment] 2018-04-05 09:10
Thanks for reporting this! It's a duplicate of #291, so I'll close this.

**Closed by SteveSandersonMS** 2018-04-05 09:10 UTC
