### ISSUE TITLE
Using C# expression in event handler attribute value breaks compilation

### ISSUE THREAD

**Issue by Knudel** [aspnet/Blazor#1635] opened 2018-11-03 12:53 UTC
When you pass a c# property to a javacript function you get an error.

Sample:

I created a Blazor server side project.
I include a javascript file with a function:

```
function doAlert(str) {
    alert(str);
}
```

Then I create a blazor view like this:

```
@page "/"

<button onclick="doAlert(@message)">Click me</button>

@functions
{

    public string message { get; set; } = "Hello World!!!!";

}

```

When compiling I get the error:

Error	CS1525	Invalid expression term ')'

**Comment by Knudel** [comment] 2018-11-03 17:34
Hello @enetstudio,

there are situations where you don't want C# functions to be called but only pass a C# variable to a javascript function.
My real code has a drag and drop box. Because I am using server side Blazor I don't want a callback, this would only slow down everything. I just want to pass a C# variable to a javascript function, and why should  this not be possible, you can also output a variable with:

`Hello: @name`

So I can also pass a variable to a javascript function.

I would like to use only C#, but the current situation is that webassembly is not ready to completely replace javascript, so backwards compatibility should be possible and in this case the best of both worlds.

Best regards, and thank you for your comments..

**Comment by Andrzej-W** [comment] 2018-11-03 19:14
@enetstudio Unfortunately you are wrong. Blazor has support for C# and JavaScript functions.
Syntax for C# function call (without parameters)
```html
<button onclick="@doAlert">Click me</button>
```
Syntax for C# function call (with parameters)
```html
<button onclick="@(() => doAlert("Hello World"))">Click me</button>
```
Syntax for JavaScript function call
```html
<button onclick="doAlert()">Click me</button>
```
```html
<button onclick="doAlert('Hello World')">Click me</button>
```

Now let's come back to real problem.
```html
<button onclick="doAlert(@message)">Click me</button>
```
Code generated for it is really strange and I think it is a bug:
```c#
builder.AddAttribute(1, "onclick", (Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>() + "doAlert(" + (message) + ")" + ()));
```
We can change our button:
```html
<button onclick="doAlert('Hello World')">Click me</button>
```
and now program works as expected.
```c#
builder.AddAttribute(1, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>("doAlert('abc')"));
```

Now an interesting experiment. This code works!!!
```html
@page "/"
<button onclick="@message">Click me</button>
```
```c#
@functions
{
public string message { get; set; } = "doAlert('Hello World')";
}
```

**Comment by Knudel** [comment] 2018-11-03 19:49
Hello @Andrzej-W,

That last experiment is strange, it didn't expect it to work.

**Comment by enetstudio** [comment] 2018-11-08 16:06
@Andrzej-W, thanks for your post...
I didn't know that I could call a JavaScript function this way:
<button onclick="doAlert()">Click me</button>

I had the idea that I must use the IJSRuntime to call a JavaScript function, but yes you're right. Thanks for this info...

**Comment by enetstudio** [comment] 2018-11-08 16:08
@Andrzej-W, thanks for your post...
I didn't know that I could call a JavaScript function this way:
'''
<button onclick="doAlert()">Click me</button>
'''
I had the idea that I must use the IJSRuntime to call a JavaScript function, but yes you're right. Thanks for this info...

**Comment by enetstudio** [comment] 2018-11-08 16:10
@Andrzej-W, thanks for your post...
I didn't know that I could call a JavaScript function this way:

<button onclick="doAlert()">Click me</button>

I had the idea that I must use the IJSRuntime to call a JavaScript function, but yes you're right. Thanks for this info...

**Comment by enetstudio** [comment] 2018-11-08 16:13
@Andrzej-W, thanks for your post...
I didn't know that I could call a JavaScript function this way:

<button onclick="doAlert()">Click me</button>

I had the idea that I must use the IJSRuntime to call a JavaScript function, but yes you're right. Thanks for this info...

**Comment by enetstudio** [comment] 2018-11-08 16:13
@Andrzej-W, thanks for your post...
I didn't know that I could call a JavaScript function this way:
```
<button onclick="doAlert()">Click me</button>
```
I had the idea that I must use the IJSRuntime to call a JavaScript function, but yes you're right. Thanks for this info...

**Comment by danroth27** [comment] 2018-11-08 17:07
Yeah, this looks like a code gen bug.

**Comment by danroth27** [comment] 2018-11-09 18:12
Duplicate of #1530

**Closed by danroth27** 2018-11-09 18:12 UTC
Labels: bug
