### ISSUE TITLE
Add sections...

### ISSUE THREAD

**Issue by desalbres** [aspnet/Blazor#1038] opened 2018-06-25 07:03 UTC
Hello, 

Could you add @section to razor views like in ASP.NET MVC ?

Thanks,

Raphaël Desalbres

**Comment by SteveSandersonMS** [comment] 2018-06-25 09:53
We haven't decided yet whether this fits into the programming model, because components are much more powerful than what you'd normally get with sections and layouts. But in any case we're tracking the layouts design in #138 so I'll close as a duplicate of that.

**Closed by SteveSandersonMS** 2018-06-25 09:53 UTC

**Comment by desalbres** [comment] 2018-06-25 10:00
You're right, you shoud keep Blazor the simplest possible to target a broader developers audience !
I've leant angular2 and the learning curve for .NET developers seems steeper than Blazor ! Congrats of all the work done so far, can't wait to see RTM !
