### ISSUE TITLE
Blazor breaks Orchard Core CMS middleware pipeline

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Blazor#1267] opened 2018-08-06 16:55 UTC
If I just reference `Blazor.Server` it breaks Orchard Core CMS middleware I CSS is not served

Try repro in https://github.com/msproadshow/Orchard/tree/blazor-conference

TheConferenceTheme references `Blazor.Server`
Orchard.CMS.Web references TheConferenceTheme and runs.
Immediately setup screen is displayed broken.

**Comment by xperiandri** [comment] 2018-08-06 16:58
Maybe related to https://github.com/aspnet/Blazor/issues/1216

**Comment by SteveSandersonMS** [comment] 2018-08-09 10:18
Yes, closing as duplicate of #1216. Thanks for reporting it though!

**Closed by SteveSandersonMS** 2018-08-09 10:18 UTC

**Comment by xperiandri** [comment] 2018-08-09 11:17
What about a fix to that issue?

**Comment by SteveSandersonMS** [comment] 2018-08-09 12:03
If you’re asking if this is already fixed, then no sorry - that’s why #1216 is still open.
