### ISSUE TITLE
Add "Blazor Page" template to VS templates for 'Add New' dialog in VS

### ISSUE THREAD

**Issue by conficient** [aspnet/Blazor#732] opened 2018-05-02 09:32 UTC
Not an urgent requirement, but a "Blazor Page" template would be nice in the "Add New" dialog in VS.

At present I just copy existing pages and rename them.

**Comment by brunopbarrote** [comment] 2018-05-02 19:01
You mean ItemTemplate

**Comment by lohithgn** [comment] 2018-05-02 20:35
as of now i do Add New Item > Razor View in VS ... :)

**Comment by SteveSandersonMS** [comment] 2018-07-23 22:58
Duplicate of #23

**Closed by SteveSandersonMS** 2018-07-23 22:58 UTC
