### ISSUE TITLE
Binding to events to a component that inherits from a c# class broke in 0.4.0

### ISSUE THREAD

**Issue by chanan** [aspnet/Blazor#954] opened 2018-06-08 03:43 UTC
The following worked in 0.3.0:

DynamicElement is defined here: https://github.com/aspnet/Blazor/blob/stevesa/bootstrap-components-library/src/Microsoft.AspNetCore.Blazor.Bootstrap/DynamicElement.cs

```
<DynamicElement onclick="@onclick" ...>...</DynamicElement>

@functions {
  [Parameter] private Action onclick { get; set; }
}
```

in 0.4.0 an error on build:

```
Argument 1: cannot convert from 'System.MulticastDelegate' to 'string'
```

**Comment by Daddoon** [comment] 2018-06-08 13:38
I had the same error on one of my own component, actually it was because an other subcomponent was still using the **public** accessor syntax instead of the **private** one with the **[Parameter]** attribute.

As i don't use the DynamicElement component, i have no clue for you.

**Comment by chanan** [comment] 2018-06-08 23:56
Not 100% sure but this seems to be the problematic line in <File>.g.cs files:

```
builder.AddAttribute(3, "onclick", Microsoft.AspNetCore.Blazor.Components.RuntimeHelpers.TypeCheck<System.String>(Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>(onclick)));
```

**Comment by Daddoon** [comment] 2018-06-09 13:30
I don't have took a look but maybe the OnClick property attribute on the base component may not have upgraded to the new signature type ?

**Comment by danroth27** [comment] 2018-06-12 05:52
@SteveSandersonMS Thoughts on this one?

**Comment by SteveSandersonMS** [comment] 2018-06-12 09:54
I haven't investigated it yet, but cc @rynowak in case it's immediately obvious to him.

**Comment by rynowak** [comment] 2018-06-14 19:31
What if you try `Action<UIMouseEventArgs>`>?

**Comment by chanan** [comment] 2018-06-15 13:32
@rynowak Same error.

**Comment by Andrzej-W** [comment] 2018-06-15 14:07
I have cloned your project and for me Blazor4Test compiles and works as expected.
- VS 15.7.3
- Blazor 0.4.0
- .NET Core 2.1 (dotnet --version displays 2.1.300)

Your project looks like default starting project without any changes. Am I missing something?

**Comment by chanan** [comment] 2018-06-15 14:12
Oops, forgot to push. Sorry about that. The issue is on ButtonTest.cshtml

**Comment by Andrzej-W** [comment] 2018-06-15 21:30
@rynowak In Blazor 0.4.0 you have added this file:
```
Blazor\src\Microsoft.AspNetCore.Blazor\Components\RuntimeHelpers.cs
```
with this function inside
```C#
public static T TypeCheck<T>(T value) => value;
```
I don't know what code was generated in Blazor 0.3.0 but now in
```
Blazor4Test\obj\Debug\netstandard2.0\Pages\ButtonTest.g.cs 
```
file we have something like this:
```C#
builder.AddAttribute(3, "OnClick", Microsoft.AspNetCore.Blazor.Components.RuntimeHelpers.TypeCheck<System.String>(Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>(OnClick)));
```
and that is why we get
```
Argument 1: cannot convert from 'System.MulticastDelegate' to 'string'
```
Maybe @SteveSandersonMS  will be able to help here (author of DynamicElement).

**Comment by rynowak** [comment] 2018-06-15 22:50
Assigning myself to look into this. 

I think I'll have to understand a bit more about the design of dynamic element. What's going on is that the type checking expects this parameter to be a string, even though it's obviously not.

It's possible that I messed up the type checking for *extra* parameters by type checking them as strings, when they could be all kinds of things.

**Comment by Andrzej-W** [comment] 2018-06-16 01:30
I have applied a few changes to DynamicElement as suggested by @Daddoon 
> I had the same error on one of my own component, actually it was because an other subcomponent was still using the public accessor syntax instead of the private one with the [Parameter] attribute.

```c#
-       public string TagName { get; set; }
+       [Parameter]
+       private string TagName { get; set; }
 
-       public Action<UIMouseEventArgs> OnClick { get; set; }
+       [Parameter]
+       private Action<UIMouseEventArgs> OnClick { get; set; }
 
        /// <summary>
        /// Gets or sets the attributes to render.
        /// </summary>
-       public IReadOnlyDictionary<string, object> Attributes
+       [Parameter]
+       private IDictionary<string, object> Attributes
```
I have also removed this
```c#
public Action<UIMouseEventArgs> OnClick { get; set; }
```
from BootstrapComponentBase.
Now I'm able to compile and run your test application, but there are at least two problems:

- button is not rendered correctly (probably ChildContent is not rendered inside button)
- I see runtime exception in browser console when I click on the button (SyntaxError: unexpected token: numeric literal)

@rynowak Temporarily it looks that it is not your fault, but please don't close this yet. It is possible that there are some other bugs somewhere in Blazor or in @chanan 's source code. Unfortunately it is 3:30am in Poland and I have to go to bed 😪

**Comment by chanan** [comment] 2018-06-18 17:48
The problem with that solution is that:

1. You would need to provide properties for each possible attribute
2. You would need to then throw an unsupported exception for those properties that don't actually make sense base on tag name.

While doable, no ideal.

But also, as you say at the end, it still doesnt work right :)

So, I would say, yes this is still an issue due to the fact that the purposed workaround still doesn't fully work.

**Comment by chanan** [comment] 2018-07-03 14:03
@rynowak Is this likely to be fixed soon? I am really stuck with this in both https://github.com/chanan/BlazorStrap and to a bit lesser extant on https://github.com/chanan/Blazorous

**Comment by Daddoon** [comment] 2018-07-03 15:03
As a temporary workaround, you may try to change the private value via reflection + StateHasChanged ? But it's a very quirck solution...

**Comment by rynowak** [comment] 2018-07-03 17:01
I'll take a look at this today

**Comment by rynowak** [comment] 2018-07-04 01:11
OK, I've been able to reproduce this, looking at a fix that will drop the type check any type an attribute is 'weakly typed'.

**Comment by rynowak** [comment] 2018-07-05 16:15
This should be fixed now in the dev branch

**Closed** 2018-07-05 16:15 UTC
Labels: bug, investigate
