### ISSUE TITLE
System.Linq.Expressions is unavailable

### ISSUE THREAD

**Issue by rockfordlhotka** [aspnet/Blazor#513] opened 2018-04-08 18:59 UTC
Some libraries (like Newtonson.Json and CSLA .NET) use `System.Linq.Expressions` to optimize/avoid the use of reflection.

Currently these libraries won't work in Blazor because it appears that `System.Linq.Expressions` doesn't work. Perhaps just in the mono interpreter, perhaps due to another reason. In any case, this is a problematic limitation.

Note: Newtonsoft.Json appears to work when serializing simple/primitive types, but not when working against complex/custom types.

**Comment by Daddoon** [comment] 2018-04-08 21:03
Duplicate of #356 ?
You may found a workaround in this thread for this issue.

**Closed** 2018-04-08 21:27 UTC
