### ISSUE TITLE
C# variables used in script generate broken code

### ISSUE THREAD

**Issue by pnary** [aspnet/Blazor#482] opened 2018-04-04 13:01 UTC
Using a c# variable inside a script tag seems to add a newline before and after the variable.

Example:

<script>console.log('@helloWorld');</script>

@functions{
	string helloWorld = "Hello world";
}

Generates:

console.log('
Hello world
');

at runtime.

**Comment by rynowak** [comment] 2018-04-04 14:48
I'll take a look at this, this doesn't seem intended.

**Comment by rynowak** [comment] 2018-04-04 15:30
I can confirm that I can reproduce this. There's also an exception being thrown from the js side:
```
VM399:1 Uncaught SyntaxError: Invalid or unexpected token
    at insertNodeIntoDOM (BrowserRenderer.ts:284)
    at BrowserRenderer.insertText (BrowserRenderer.ts:168)
    at BrowserRenderer.insertFrame (BrowserRenderer.ts:101)
    at BrowserRenderer.insertFrameRange (BrowserRenderer.ts:264)
    at BrowserRenderer.insertElement (BrowserRenderer.ts:132)
    at BrowserRenderer.insertFrame (BrowserRenderer.ts:98)
    at BrowserRenderer.applyEdits (BrowserRenderer.ts:44)
    at BrowserRenderer.updateComponent (BrowserRenderer.ts:25)
    at renderBatch (Renderer.ts:45)
    at Array.<anonymous> (mono.js:1)
```

**Comment by rynowak** [comment] 2018-04-04 17:17
What happens is that each 'chunk' of content is added to the dom in sequence, which breaks inside script tags when a chunk isn't well-formed. This chunk-wise handling required so that we can do minimal diffs of the dom and apply only the edits that are necessary.

If you want to work around this for now I'd suggest building your whole script in a single value like:
```
<script>@GetScript()</script>
@functions{

    public string GetScript()
    {
        return $"console.log('{Message}');";
    }

    public string Message => "hello world";
}"
```

**Comment by SteveSandersonMS** [comment] 2018-04-04 22:55
Thanks for the info @rynowak!

I hope this explains why it's not a supported scenario (and in general why it's undesirable to put `<script>` tag inline into components for just about any reason) so I'll close this for now.

If other people report similar issues then it would imply we need to do more to meet people's expectations better, so we'd review at that point. Hope that's OK!

**Closed by SteveSandersonMS** 2018-04-04 22:55 UTC
