### ISSUE TITLE
cannot set attributes where the name contains a hyphen using Razor syntax - compilation error

### ISSUE THREAD

**Issue by yowl** [aspnet/Blazor#497] opened 2018-04-05 21:44 UTC
With this code:
`<button  data-target="@detailsId" >Click me</button>`
Compilation fails with
`Error	CS1503	Argument 2: cannot convert from 'string' to 'Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeFrame'	`
Code behind is:
```
            builder.OpenElement(9, "button");
            builder.AddAttribute(10, "data-target", "");
            builder.AddAttribute(11, detailsId);
            builder.AddContent(12, "Click me");
            builder.CloseElement()
```

Change code to 
`<button  datatarget="@detailsId" >Click me</button>`
and its fine.

This looks similar to #496 because of the builder code, but I'm not sure.

**Comment by rynowak** [comment] 2018-04-05 22:24
Hi @yowl this is specific to `data-` attributes, and we're working on removing this limitation. The fix has to come from Razor first and then make its way into VS.

Closing this as a duplicate of #219

You can work around this problem for now using `data_` in place of `data-`
https://github.com/aspnet/Blazor/commit/c16263fb13cc3781b08aad957a3f64bd23851be0#diff-176e3183ed2eecdbc868099d850ef2ccR549

**Closed by rynowak** 2018-04-05 22:24 UTC

**Comment by yowl** [comment] 2018-04-05 22:33
I should have seen that one, thanks.
