### ISSUE TITLE
Consider supporting the ability to mix Blazor components and MVC/static pages

### ISSUE THREAD

**Issue by Gorea235** [aspnet/Blazor#596] opened 2018-04-18 01:16 UTC
Currently, Blazor seems to be aiming to compete in a very similar way to Angular, where the entire app is purely written in Blazor and nothing else. While is this good (and would be very cool to use), it might also be good to allow 'mixing' of Blazor components/logic, with normal pages that are generated or static. Similar to how jQuery works, or how React allows you to render components to certain points in the page, rather than requiring the entire app to be built using React.

The primary benefit of allowing a 'drop-in' system would be to enable developers to add in Blazor post-development in order to all a dynamic component to the site, without having to rewrite the entire thing from the ground up, which makes it much more appealing to developers who are currently maintaining sites, and might also increase interest in the project.

Would this be possible? Or is it being considered already? And, how would this kind of system work (as the current system seems to be very focused on the 'ground-up' approach)?

**Comment by DNF-SaS** [comment] 2018-04-20 10:11
If I'm right, Blazor's bootscript replaces the content of the <app /> element with it's blazor-components.
So it's pretty the same approach like React has.
Little drawback: using React, you can additionally specify the container-element which it replaces, Blazor seems to be fixed to <app />.
So IMO, it should be already possible to mix Blazor with static pages.

**Comment by SteveSandersonMS** [comment] 2018-04-20 17:02
> Little drawback: using React, you can additionally specify the container-element which it replaces, Blazor seems to be fixed to .

It's not fixed. When you instantiate a `BrowserRenderer`, you pass the CSS selector of the element you want to mount it inside. You can have as many different `BrowserRenderer` instances as you want, and associate them with different parts of the page.

The remaining work to make this easy is covered in #108, so I'll close as a duplicate of that.

**Closed by SteveSandersonMS** 2018-04-20 17:02 UTC
