### ISSUE TITLE
I take an error blazor.boot.json not found

### ISSUE THREAD

**Issue by bariscanyilmaz** [aspnet/Blazor#1469] opened 2018-09-23 12:53 UTC
I create new blazor prıject in serverside asp.net core and i start project it's not working 
and 
![blazor](https://user-images.githubusercontent.com/30300440/45928195-48849880-bf48-11e8-8f0f-25b3329c86ab.PNG)
i try this solution it is not working. i download blazor project from codeproject. its blazor server version is 0.4 and i run this it is working
can any dody solve this

**Comment by SteveSandersonMS** [comment] 2018-09-24 14:07
I'm afraid I don't know what would cause this, as it doesn't happen for me, nor has this been reported before.

Can you check that you have the required version of the .NET Core SDK and other prerequisites? (Note: not newer versions, until we release Blazor 0.6.0) https://blazor.net/docs/get-started.html

**Comment by bariscanyilmaz** [comment] 2018-09-25 06:47
i check prerequrities and i have .net core 2.1.402 
![dotnetversion](https://user-images.githubusercontent.com/30300440/45997300-c8754480-c0a7-11e8-8f0b-775ab6b2b9ab.PNG)
threre is my installled templates
![templates](https://user-images.githubusercontent.com/30300440/45997383-0c684980-c0a8-11e8-807a-a5b1388e07ad.PNG)

**Comment by SteveSandersonMS** [comment] 2018-09-25 08:02
With Blazor 0.5.1 please use .NET Core SDK 2.1.302. The issues with newer SDKs should be resolved in Blazor 0.6.0.

**Comment by bariscanyilmaz** [comment] 2018-09-25 12:03
i uninstall dotnet 2.1.402 and now i have dotnet 2.1.302
![dotnetversion](https://user-images.githubusercontent.com/30300440/46013123-f1133380-c0d3-11e8-8ed1-845aad56f241.PNG)
but i take same error
![blazor](https://user-images.githubusercontent.com/30300440/46013157-1607a680-c0d4-11e8-916b-de236b8728f0.PNG)

**Comment by danroth27** [comment] 2018-09-26 06:13
It looks like the *blazor.boot.json* file isn't being created correctly for some reason. 

Can you share your project with us?

**Comment by bariscanyilmaz** [comment] 2018-09-26 07:05
https://github.com/bariscanyilmaz/blazorIssue my blazor project

**Comment by SteveSandersonMS** [comment] 2018-09-26 10:19
Thanks for posting the repro project.

The reason it's not generating the boot JSON file is that it doesn't compile at all, so you're loading a result of an earlier compilation that doesn't match up with your current sources. When building there are compiler errors such as:

```
The type or namespace name 'Shared' does not exist in the namespace 'blazor302' (are you missing an assembly reference?)
```

The reason for these compiler errors is that you've renamed your project since it was first created (from `blazor302` to `blazorIssue`, I'm guessing), but didn't correspondingly change all the old references to `blazor302` to `blazorIssue`.

To fix this, you can find-replace-in-all-files from `blazor302` to `blazorIssue` then rebuild. It should then compile without errors. If you continue to have trouble, I'd recommend creating a new project to ensure the names in it are consistent.

**Closed by SteveSandersonMS** 2018-09-26 10:19 UTC

**Comment by bariscanyilmaz** [comment] 2018-09-26 11:40
i change git repo name to blazor302. i command dotnet build and run  but i take same error. https://github.com/bariscanyilmaz/blazor302

**Comment by SteveSandersonMS** [comment] 2018-09-26 12:03
Thanks for the update. In that case, I'm afraid there's some other issue that's breaking the dev environment on your machine. When I clone your repo, delete both `bin` and `obj` then rebuild, it works correctly.

If you have any idea what might be causing the problem in your dev environment, or steps to reproduce it on other machines, please let us know. Likewise if anyone else is seeing this please tell us in case this is not limited to the one case.

**Comment by bariscanyilmaz** [comment] 2018-09-26 12:18
thank you for your effort.

**Comment by bartczernicki** [comment] 2019-07-26 18:26
@danroth27 @SteveSandersonMS 
I am seeing this issue as well in Preview 7.  It started happening more (since upgrading from Preview 6).  Deployed to Azure with App Insights and GET /_framework/blazor.boot.json is failing.  After re-freshing browser and waiting a few seconds it seems to work.  The issue seems like it is intermittent.

**Comment by danroth27** [comment] 2019-07-26 23:04
Hi @bartczernicki. For us to help you out were going to need more details on how to reproduce the issue. If you are able to reproduce this behavior consistently, please open a new issue in the https://github.com/aspnet/aspnetcore/issues repo with the detailed info on your environment and your app and we'll take a look.

**Comment by bartczernicki** [comment] 2019-07-26 23:36
@danroth27 thanks Dan.  Opened a new issue:
https://github.com/aspnet/AspNetCore/issues/12637
