### ISSUE TITLE
support for dynamic keyword

### ISSUE THREAD

**Issue by kai-oswald** [aspnet/Blazor#436] opened 2018-03-29 18:28 UTC
I recently tried using blazor with the `dynamic` keyword. The compilation is succesful, but the page stays empty. Is support for `dynamic` planned or am I missing something and there is a workaround to use `dynamic`?

**Comment by kai-oswald** [comment] 2018-03-29 22:29
The following steps will reproduce the issue:
- Create new Blazor Project
- Add `Microsoft.CSharp` Nuget
- Add Razor View:
```C#
@page "/dynamic"

<h2>@test</h2>

@functions {
    dynamic test = "this won't show";
}
```

**Comment by Suchiman** [comment] 2018-03-30 23:41
@kai-oswald it does work, but it seems you missed the compiler error  
`obj\Debug\netstandard2.0\Pages\Index.g.cs(36,13,36,20): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'`

Just add these to the blazor csproj to fix it:
```csproj
    <PackageReference Include="System.Dynamic.Runtime" Version="4.3.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.4.1" />
```

**Comment by SteveSandersonMS** [comment] 2018-04-05 15:43
After adding the two package (`System.Dynamic.Runtime` and `Microsoft.CSharp`), the code works fine with linking disabled (`<BlazorLinkOnBuild>false</BlazorLinkOnBuild>` in the csproj), but fails to compile if linking is enabled. The error is:

```
Cannot find declaration of exported type 'System.Threading.Semaphore' from the assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  Cannot find declaration of exported type 'System.Reflection.Emit.DynamicMethod' from the assembly 'System.Reflection.Emit.Lightweight, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
``

Therefore I'll close this as a duplicate of #365.

**Closed by SteveSandersonMS** 2018-04-05 15:43 UTC

**Comment by danroth27** [comment] 2018-04-05 17:35
@SteveSandersonMS Did you link to the correct bug? How is this related to the Windows Defender issue?
